# Generated by Django 4.0.10 on 2025-11-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_researcher',
            field=models.BooleanField(default=False, verbose_name='Статус сотрудника (исследователя)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
