# Generated by Django 4.0.10 on 2025-11-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта исследования')),
                ('a_0', models.FloatField(verbose_name='Значение коэффициента a0')),
                ('a_1', models.FloatField(verbose_name='Значение коэффициента a1')),
                ('a_2', models.FloatField(verbose_name='Значение коэффициента a2')),
                ('a_3', models.FloatField(verbose_name='Значение коэффициента a3')),
                ('a_4', models.FloatField(verbose_name='Значение коэффициента a4')),
                ('a_5', models.FloatField(verbose_name='Значение коэффициента a5')),
                ('a_6', models.FloatField(verbose_name='Значение коэффициента a6')),
                ('a_7', models.FloatField(verbose_name='Значение коэффициента a7')),
                ('a_8', models.FloatField(verbose_name='Значение коэффициента a8')),
            ],
            options={
                'verbose_name': 'Математическая модель',
                'verbose_name_plural': 'Математические модели',
            },
        ),
    ]
